<?php
require_once(__DIR__ . '/../db.php');

// Your OpenAI API Key
$openai_api_key = '<KEY HERE>';

$prompt = "Generate a random task for a task management app";

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.openai.com/v1/chat/completions");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    'model' => 'gpt-3.5-turbo',
    'messages' => [
        ['role' => 'system', 'content' => 'You are a task generator assistant.'],
        ['role' => 'user', 'content' => $prompt]
    ],
    'max_tokens' => 100
]));

curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json',
    'Authorization: Bearer ' . $openai_api_key
]);

$response = curl_exec($ch);
curl_close($ch);

$response_data = json_decode($response, true);

// Check if response contains the generated task
// if (isset($response_data['choices']) && isset($response_data['choices'][0]['message']['content'])) {
//     $generated_task = trim($response_data['choices'][0]['message']['content']);
    
//     echo json_encode([
//         'success' => true,
//         'generatedTask' => $generated_task
//     ]);
// } else {
//     echo json_encode([
//         'success' => false,
//         'message' => 'Failed to generate task. OpenAI API response was invalid.',
//         'generatedTask' => null
//     ]);
// }


// Get the text generated by OpenAI
//$generatedText = $response['choices'][0]['text'] ?? 'No task generated';

// Add the generated task to the database
//$title = trim($generatedText);  // Assume the whole text is the title for simplicity
//$description = 'This task was generated by AI';
//$status = 'pending';

// Insert into the database
// $sql = "INSERT INTO tasks (title, description, status) VALUES ('$title', '$description', '$status')";
// if (mysqli_query($conn, $sql)) {
//     echo json_encode([
//         'success' => true,
//         'message' => 'AI-generated task added successfully!',
//         'generatedTask' => [
//             'title' => $title,
//             'description' => $description,
//             'status' => $status,
//         ],
//     ]);
// } else {
//     echo json_encode([
//         'success' => false,
//         'message' => 'Failed to add the AI-generated task to the database.',
//         'generatedTask' => null,
//     ]);
// }

// mysqli_close($conn);
?>
